openapi: 3.0.1
info:
  title: VPP Agent Memif Interface
  description: VPP Agent GET Memif Interface REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/interfaces/memif:
    get:
      summary: list of Memif Interfaces
      description:
      responses:
        '200':
          description: list of Memif Interfaces
          content:
            application/json:
              schema:
                type: array
                description: list of Memif Interfaces
                items:
                  type: object
                  properties:
                    sw_if_index value:
                      type: object
                      description: sw_if_index value used to index array of interface objects
                      properties:
                        interface:
                          type: object
                          description: properties fields defined in proto/ligato/vpp/interfaces/interface.pb.go
                          properties:
                            name:
                              type: string
                              example: mem01
                              description: logical name for the interface, must be unique across all configured VPP interfaces
                            type:
                              type: string
                              required: boolean
                              description: interface type and must match actual link
                              enum:
                                - UNDEFINED_TYPE
                                - SUB_INTERFACE
                                - SOFTWARE_LOOPBACK
                                - DPDK
                                - MEMIF
                                - TAP
                                - AF_PACKET
                                - VXLAN_TUNNEL
                                - VMXNET3_INTERFACE
                                - BOND_INTERFACE
                                - GRE_TUNNEL
                                - GTPU_TUNNEL
                                - IPIP_TUNNEL
                              example: MEMIF
                            enabled:
                              type: boolean
                              description: Enabled controls if the interface should be UP
                              example: true
                            physAddress:
                              type: string
                              description: interface physical address; random address assigned if left empty
                              example: 02:00:00:00:00:03
                            ipAddresses:
                              type: string
                              description: IPAddresses define list of IP addresses for the interface and must be defined in the format of <ipAddress>/<ipPrefix>.
                              example: 172.30.1.1/24
                            vrf:
                              type: integer
                              description: ID of VRF table that the interface is assigned to.
                              example: 0
                            set_dhcp_client:
                              type: boolean
                            mtu:
                              type: integer
                              example: 1500
                              description: maximum frame size on wire
                            unnumbered:
                              type: string
                              description: unnumbered interface
                              properties:
                                interfaceWithIp:
                                  type: string
                                  description: name of interface to borrow IP address from
                            rxModes:
                              type: object
                              description: rx mode for interface
                              properties:
                                queue:
                                  type: integer
                                  example: 1
                                mode:
                                  type: string
                                  enum:
                                    - UNKNOWN
                                    - POLLING
                                    - INTERRUPT
                                    - ADAPTIVE
                                    - DEFAULT
                                  example: ADAPTIVE
                                defaultMode:
                                  type: boolean
                            rxPlacements:
                              type: object
                              description: rxPlacement
                              properties:
                                queue:
                                  type: integer
                                  example: 1
                                worker:
                                  type: integer
                                  example: 1
                                mainThread:
                                  type: boolean
                            memifLink:
                                $ref: '#/components/schemas/memifLink'
                        interface_meta:
                                $ref: '#/components/schemas/interface_meta'
        '404':
           description: error
           content:
             application/json:
               schema:
                 type: string
                 description: error message
                 example: not found
components:
  schemas:
    memifLink:
      type: object
      description:  MemifLink fields defined in ../proto/ligato/vpp/interfaces/interface.proto
      properties:
        mode:
          type: string
          enum:
            - ETHERNET
            - IP
            - PUNT_INJECT
        master:
          type: boolean
          example: true
        id:
          type: integer
          description: 32bit integer used to authenticate and match opposite sides of the connection
        socketFilename:
          type: string
          description: Filename of the socket used for connection establishment
        secret:
          type: string
        ringSize:
          type: integer
          description: number of entries of RX/TX rings
        bufferSize:
          type: integer
          description: size of the buffer allocated for each ring entry
        rxQueues:
          type: integer
          description: number of rx queues (only valid for slave)
        txQueues:
          type: integer
          description: number of tx queues (only valid for slave)
    interface_meta:
      type: object
      description: properties defined in plugins/vpp/ifplugin/vppcalls/interface_handler_api.go
      properties:
        sw_if_index:
          type: integer
          description: sw_if_index used to index array of interface objects
          example: 3
        sub_sw_if_index:
          type: integer
          example: 3
        l2_address:
          type: string
          example: NDwAAAAB
        internal_name:
          type: string
          example: tap0
        is_admin_state_up:
          type: boolean
          example: true
        is_link_state_up:
          type: boolean
          example: true
        link_duplex:
          type: integer
          example: 0
        link_mtu:
          type: integer
          example: 1450
        mtu:
          type: object
          description: per-protocol mtu for L2,
          example: [1450, 0,0,0]
        link_speed:
          type: integer
          example: 0
        sub_id:
          type: integer
          example: 0
        tag:
          type: string
          example: tap-vpp2
        dhcp:
          nullable: boolean
          example: null
          # look into handling with component
        vrf_ipv4:
          type: integer
          example: 0
        vrf_ipv6:
          type: integer
          example: 0
        pci:
          type: uin32
          example: 0


