openapi: 3.0.1
info:
  title: VPP Agent Linux Interfaces
  description: VPP Agent GET Linux Interfaces REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/linux/v2/interfaces:
    get:
      summary: Returns a list of configured Linux Interfaces
      description: VPP Agent Linux Interfaces info
      responses:
        '200':
          description: Returns a list of configured Linux Interfaces
          content:
            application/json:
              schema:
                type: array
                description: list of configured Linux Interfaces
                items:
                  type: object
                  description: an individual Linux Interface and meta object
                  properties:
                    interfaces:
                      type: object
                      properties:
                          name:
                            type: string
                            example: tap-vpp1
                          type:
                            type: string
                            example: TAP_TO_VPP
                          hostIfName:
                            type: string
                            example: vpp1
                          enabled:
                            type: boolean
                            example: true
                          ipAddresses:
                            type: array
                            description: IPAddresses define list of IP addresses for the interface and must be defined in the following format of <ipAddress>/<ipPrefix>
                            items:
                              type: string
                              format: ipv4
                              example: 171.13.6.1
                          arp_termination:
                            type: boolean
                            example: true
                          mac_age:
                            type: uint32
                            example: 364
                          interfaces:
                            type: object
                            description: interface that BD is assigned to
                            properties:
                              name:
                                type: string
                                example: loop1
                              bridged_virtual_interface:
                                type: boolean
                                example: true
                              split_horizon_group:
                                type: uint32
                                example: 22
                          arp_termination_table:
                            type: object
                            description: ARP entries for tunnel termination
                            properties:
                                  ip_address:
                                    type: string
                                    example: 192.16.18.01
                                  phys_address:
                                    type: string
                                    example: 03:19:00:00:55:01
                    bridge_domain_meta:
                      type: object
                      properties:
                        bridge_domain_id:
                          type: integer
                          example: 1
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found