openapi: 3.0.1
info:
  title: VPP Agent Linux Routes
  description: VPP Agent GET Linux Routes REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/linux/v2/routes:
    get:
      description: linux route entries
      responses:
        '200':
          description: linux route entries
          content:
            application/json:
              schema:
                type: array
                description: linux route and meta data
                items:
                  type: object
                  description: linux route and meta data
                  properties:
                    routes:
                      type: object
                      properties:
                          outgoing_interface:
                            type: string
                            example: tap-vpp1
                          scope:
                            type: string
                            enum:
                              - UNDEFINED = 0;
                              - GLOBAL = 1;
                              - SITE = 2;
                              - LINK = 3;
                              - HOST = 4;
                            example: GLOBAL
                          dst_network:
                            type: string
                            example: 10.1.0.0/16
                          gw_addr:
                            type: string
                            example: 172.30.1.1
                          metric:
                            type: integer
                            format: uint32
                            example: 1
                    Meta:
                      type: object
                      properties:
                        interface_index:
                          type: integer
                          format: uint32
                          example: 7
                        link_scope:
                          type: integer
                          format: uint32
                          example: 0
                        protocol:
                          type: integer
                          format: uint32
                          example: 3
                        mtu:
                          type: integer
                          format: uint32
                          example: 0
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found

