openapi: 3.0.1
info:
  title: Ligato VPP Agent REST APIs
  description: Describes the REST APIs supported by the Ligato VPP Agent
  version: 3.0
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
tags:
  - name: Ligato VPP Agent
paths:
  /dump/linux/v2/arps:
    get:
      description: linux arp entries
      tags:
        - Linux L3 Plugin
      responses:
        '200':
          description: linux arp entries
          content:
            application/json:
              schema:
                type: array
                description: linux arp and meta data
                items:
                  type: object
                  description: an individual Linux Interface and meta object
                  properties:
                    linux_arp:
                      type: object
                      properties:
                        interface:
                          type: string
                          example: linux-tap-61c
                        ip_address:
                          type: string
                          example: 10.1.1.1
                        hw_address:
                          type: string
                          example: 02:fe:af:aa:51:e6
                    linux_arp_meta:
                      type: object
                      properties:
                        interface_index:
                          type: integer
                          format: uint32
                          example: 7
                        ip_family:
                          type: integer
                          format: uint32
                          example: 2
                        vni:
                          type: integer
                          format: uint32
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error
  /dump/linux/v2/routes:
    get:
      description: linux route entries
      tags:
        - Linux L3 Plugin
      responses:
        '200':
          description: linux route entries
          content:
            application/json:
              schema:
                type: array
                description: linux route and meta data
                items:
                  type: object
                  description: linux route and meta data
                  properties:
                    routes:
                      type: object
                      properties:
                          outgoing_interface:
                            type: string
                            example: tap-vpp1
                          scope:
                            type: string
                            enum:
                              - UNDEFINED
                              - GLOBAL
                              - SITE
                              - LINK
                              - HOST
                            example: GLOBAL
                          dst_network:
                            type: string
                            example: 10.1.0.0/16
                          gw_addr:
                            type: string
                            example: 172.30.1.1
                          metric:
                            type: integer
                            format: uint32
                            example: 1
                    Meta:
                      type: object
                      properties:
                        interface_index:
                          type: integer
                          format: uint32
                          example: 7
                        link_scope:
                          type: integer
                          format: uint32
                          example: 0
                        protocol:
                          type: integer
                          format: uint32
                          example: 3
                        mtu:
                          type: integer
                          format: uint32
                          example: 0
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error

