openapi: 3.0.1
info:
  title: VPP Agent MACIP ACL
  description: VPP Agent GET MACIP ACL REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/acl/macip:
    get:
      summary:
      description:
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: array
                description: acl entries
                items:
                  type: object
                  description: ACL
                  properties:
                    acl:
                      type: object
                      properties:
                          name:
                            type: string
                            description: The name of an access list. A device MAY restrict the length and value of this name, possibly spaces and special characters are not allowed.
                            example: acl1
                          rules:
                             $ref: '#/components/schemas/rules'
                          interfaces:
                             $ref: '#/components/schemas/interfaces'
                    acl_meta:
                      $ref: '#/components/schemas/acl_meta'
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found
components:
  schemas:
    acl_meta:
        type: object
        properties:
          acl_index:
            type: integer
            example: 0
          acl_tag:
            type: string
            example: acl1
    rules:
      type: array
      description: List of access list entries (Rules). Each Access Control Rule has a list of match criteria and a list of actions.
      items:
        type: object
        properties:
          action:
            type: string
            description: action rule value
            enum:
              - 0 is "DENY",
              - 1 is "PERMIT",
              - 2 is "REFLECT",
            example: 1
          mac_rule:
            type: object
            properties:
              source_address:
                type: string
                example: 10.0.1.2
              source_address_prefix:
                type: integer
                format: uint32
                example: 28
              source_mac_address:
                type: string
                description: Before source-mac-address is compared with source mac address field of the packet
                  // being matched, source-mac-address-mask is applied to packet field value
                example: 03:11:22:46:17:01
              source_mac_address_mask:
                type: string
                description: Source MAC address mask.
                  // Applied as logical AND with source mac address field of the packet being matched,
                  // before it is compared with source-mac-address.
                example: 03:11:22:46:17:01
    interfaces:
      type: object
      properties:
        egress:
          type: array
          description: egress interfaces where ACL is applied
          items:
            type: string
            example: tap1
        ingress:
          type: array
          description: ingress interfaces where ACL is applied
          items:
            type: string
            example: tap2

            