openapi: 3.0.1
info:
  title: VPP Agent ACL
  description: VPP Agent GET ACL REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/acl/ip:
    get:
      summary:
      description:
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: array
                description: acl entries
                items:
                  type: object
                  description: ACL
                  properties:
                    acl:
                      type: object
                      properties:
                          name:
                            type: string
                            example: first
                          rules:
                            type: array
                            items:
                              type: object
                              properties:
                                action:
                                  type: string
                                  example: 1
                                ip_rule:
                                  type: object
                                  properties:
                                    ip:
                                      type: object
                                      properties:
                                        destination_network:
                                          type: string
                                          example: 10.20.1.0/24
                                        source_network:
                                          type: string
                                          example: 192.168.1.2/32
                                    tcp:
                                      type: object
                                      example: sling
                          interfaces:
                            type: string
                            example: interfaces object
                          3rd_prop:
                            type: object
                            description: description text
                            properties:
                              3a_prop:
                                type: string
                                example: "3a"
                              reference:
                                type: string
                                example: "/reference_string"
                          4th_prop:
                            type: string
                            example: number4
                          5th_prop:
                            type: array
                            description: array with no name value; "5thprop':' [val1, val2, ...]"
                            items:
                              type: string
                              format: ipv4
                              example: 192.168.22.1/24
                          6th_prop:
                            type: array
                            description: array with key value pairs
                            items:
                              type: object
                              properties:
                                first_name:
                                  type: string
                                  example: joe
                                last_name:
                                  type: string
                                  example: smith
                    acl_meta:
                      $ref: '#/components/schemas/interface_meta'
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found
components:
  schemas:
    interface_meta:
        type: object
        properties:
          first_meta_prop:
            type: integer
            example: 6
          second_meta_prop:
            type: integer
            example: 0
