openapi: 3.0.1
info:
  title: VPP Agent L2 Bridge Domain
  description: VPP Agent GET Bridge Domains REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/bd:
    get:
      summary: Returns a list of configured L2 Bridge Domains
      description: VPP agent bridge domain info
      responses:
        '200':
          description: List of configured bridge domains
          content:
            application/json:
              schema:
                type: array
                description: List of Bridge Domains
                items:
                  type: object
                  description: an individual bridge domain with BD and BD meta data properties
                  properties:
                    bridge_domain:
                      type: object
                      properties:
                          name:
                            type: string
                            example: bd1
                          flood:
                            type: boolean
                            example: true
                          unknown_unicast_flood:
                            type: boolean
                            example: true
                          forward:
                            type: boolean
                            example: true
                          learn:
                            type: boolean
                            example: true
                          arp_termination:
                            type: boolean
                            example: true
                          mac_age:
                            type: integer
                            format: uint32
                            example: 364
                          interfaces:
                            type: object
                            description: interface that BD is assigned to
                            properties:
                              name:
                                type: string
                                example: loop1
                              bridged_virtual_interface:
                                type: boolean
                                example: true
                              split_horizon_group:
                                type: integer
                                format: uint32
                                example: 22
                          arp_termination_table:
                            type: object
                            description: ARP entries for tunnel termination
                            properties:
                                  ip_address:
                                    type: string
                                    example: 192.16.18.01
                                  phys_address:
                                    type: string
                                    example: 03:19:00:00:55:01
                    bridge_domain_meta:
                      type: object
                      properties:
                        bridge_domain_id:
                          type: integer
                          example: 1
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found