openapi: 3.0.1
info:
  title: VPP Agent L2 FIB
  description: VPP Agent GET L2FIB REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/fib:
    get:
      summary: Returns a list of configured L2FIBs
      description: VPP agent L2FIB info
      tags:
        - L2 Plugin
      responses:
        '200':
          description: List of configured L2FIBs
          content:
            application/json:
              schema:
                type: array
                description: List of L2FIBs
                items:
                  type: object
                  properties:
                    dest MAC Address value:
                      type: object
                      description: destination MAC Address used to index VPP L2 FIB table entries into the northbound API data structure map indexed by destination MAC address
                      properties:
                        fib:
                          type: object
                          properties:
                              phys_address:
                                type: string
                                example: 12:2b:00:00:00:01
                              bridge_domain:
                                type: string
                                example: vxlanBD
                              action:
                                type: string
                                required: boolean
                                description: action (forward or drop) to take on matching frames
                                enum:
                                  - FORWARD
                                  - DROP
                                example: FORWARD
                              outgoing_interface:
                                type: string
                                example: vxlanBVI
                              static_config:
                                type: boolean
                                example: true
                              bridged_virtual_interface:
                                type: boolean
                                example: true
                        fib_meta:
                          type: object
                          properties:
                            bridge_domain_id:
                              type: integer
                              format: uint32
                              example: 1
                            outgoing_interface_sw_if_idx:
                              type: integer
                              format: uint32
                              example: 4
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error