openapi: 3.0.1
info:
  title: Ligato VPP Agent REST APIs
  description: Describes the REST APIs supported by the Ligato VPP Agent
  version: 3.0
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
tags:
  - name: Ligato VPP Agent
paths:
  /dump/vpp/v2/ipsec/sps:
    get:
      summary: Returns a list of configured IPsec security policies
      description: IPsec Security Policy (SP)
      tags:
        - IPsec Plugin
      responses:
        '200':
          description: IPsec SP data
          content:
            application/json:
              schema:
                type: array
                description: list of IPsec security policies
                items:
                  type: object
                  description: an individual IPsec security policy
                  properties:
                    spd_index:
                      type: integer
                      format: uint32
                      description: security policy database index
                      example: 1
                    sa_index:
                      type: integer
                      format: uint32
                      description: security association index
                      example: 1
                    priority:
                      type: integer
                      format: int32
                      example: 10
                    is_outbound:
                      type: boolean
                      example: true
                    remote_addr_start:
                      type: string
                      example: 0.0.0.0
                    remote_addr_stop:
                      type: string
                      example: 255.255.255.255
                    local_addr_start:
                      type: string
                      example: 0.0.0.0
                    local_addr_stop:
                      type: string
                      example: 255.255.255.255
                    protocol:
                      type: integer
                      format: uint32
                      description: 0 is Authentication Header (AH), provides a mechanism for authentication only. 1 is Encapsulating Security Payload (ESP) is for data confidentiality and authentication
                      enum:
                        - 0
                        - 1
                      example: 1
                    remote_port_start:
                      type: integer
                      format: uint32
                      example: 511
                    remote_port_stop:
                      type: integer
                      format: uint32
                      example: 615
                    local_port_start:
                      type: integer
                      format: uint32
                      example: 71
                    local_port_stop:
                      type: integer
                      format: uint32
                      example: 619
                    action:
                      type: integer
                      format: int32
                      description: See proto/ligato/vpp/ipsec/ipsec.proto for options
                      enum:
                        - 0
                        - 1
                        - 2
                        - 3
                      example: 3
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error
