openapi: 3.0.1
info:
  title: VPP Agent L3 IP Scan Neighbor
  description: VPP Agent GET L3 IP Scan Neighbor REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/ipscanneigh:
    get:
      summary: Returns Configured IP Scan Neighbor items
      description: VPP agent L3 IP Scan Neighbor info
      responses:
        '200':
          description: IP Scan Neighbor items
          content:
            application/json:
              schema:
                type: object
                description: IP Scan Neighbor Items
                properties:
                    mode:
                      type: string
                      description: ...
                      enum:
                        - DISABLED = 0;
                        - IPV4 = 1;
                        - IPV6 = 2;
                        - BOTH = 3;
                      example: 1
                    scan_interval:
                      type: integer
                      example: 1
                    max_proc_time:
                      type: integer
                      example: 20
                    max_update:
                      type: integer
                      example: 10
                    scan_int_delay:
                      type: integer
                      example: 1
                    stale_threshold:
                      type: integer
                      example: 4
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found
