openapi: 3.0.1
info:
  title: VPP Agent L3 ProxyARP Interfaces
  description: VPP Agent GET L3 Proxy ARP Interfaces REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/proxyarp/interfaces:
    get:
      summary: Returns Configured L3 Proxy ARP Interfaces
      description: VPP agent L3 Proxy ARP Interfaces info
      responses:
        '200':
          description: Proxy ARP Interface Items
          content:
            application/json:
              schema:
                type: object
                description: Proxy ARP Interface Items
                properties:
                  interfaces:
                    type: object
                    properties:
                      name:
                        type: string
                        example: tap1
                  meta:
                    type: object
                    properties:
                      swIFIndex:
                        type: integer
                        example: 1
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found
