openapi: 3.0.1
info:
  title: VPP Agent L3 ProxyARP Ranges
  description: VPP Agent GET L3 Proxy ARP Ranges REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/proxyarp/ranges:
    get:
      summary: Returns Configured L3 Proxy ARP ranges
      description: VPP agent L3 Proxy ARP ranges info
      responses:
        '200':
          description: Proxy ARP Ranges Items
          content:
            application/json:
              schema:
                type: object
                description: Proxy ARP Ranges Items
                properties:
                  ranges:
                    type: object
                    properties:
                      first_ip_addr:
                        type: string
                        example: 10.0.0.1
                      last_ip_addr:
                        type: string
                        example: 10.0.0.3
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found
