openapi: 3.0.1
info:
  title: VPP Agent L3 Route
  description: VPP Agent GET Bridge Domains REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/routes:
    get:
      summary: Returns a list of configured L3 routes
      description: VPP agent route info
      responses:
        '200':
          description: List of Configured L3 routes
          content:
            application/json:
              schema:
                type: array
                description: List of L3 routes
                items:
                  type: object
                  description: an individual route and meta properties
                  properties:
                    route:
                      type: object
                      properties:
                          type:
                            type: string
                            description: // Forwarding is being done in the specified vrf_id only, or according to
                              // the specified outgoing interface.
                              Route_INTRA_VRF Route_RouteType = 0
                              // Forwarding is being done by lookup into a different VRF,
                              // specified as via_vrf_id field. In case of these routes, the outgoing
                              // interface should not be specified. The next hop IP address
                              // does not have to be specified either, in that case VPP does full
                              // recursive lookup in the via_vrf_id VRF.
                              Route_INTER_VRF Route_RouteType = 1
                              // Drops the network communication designated for specific IP address.
                              Route_DROP Route_RouteType = 2
                            enum:
                              - "INTRA_VRF": 0,
                              - "INTER_VRF": 1,
                              - "DROP":      2,                             -
                            example: 2
                          vrf_id:
                            type: integer
                            example: 2
                          dst_network:
                            type: string
                            description: Destination network defined by IP address and prefix format of address/prefix
                            example: IPv4 is 192.168.16.1/32; IPv6 is fe80::/10
                          next_hop_addr:
                            type: string
                            example: 192.168.16.100
                          outgoing_interface:
                            type: string
                            example: GigabitEthernet0/8/0"
                          weight:
                            type: integer
                            example: 1
                          preference:
                            type: integer
                            example: 1
                          via_vrf_id:
                            type: integer
                            example: 2
                    meta:
                      type: object
                      properties:
                        TableName:
                          type: string
                          example: id/1/protocol/IPV4
                        OutgoingIfIdx:
                          type: integer
                          example: 4294967295
                        IsIPv6:
                          type: boolean
                          example: false
                        Afi:
                          type: uint8
                          example: 0
                        IsLocal:
                          type: boolean
                          example: false
                        IsUDPEncap:
                          type: boolean
                          example: false
                        IsUnreach:
                          type: boolean
                          example: false
                        IsProhibit:
                          type: boolean
                          example: false
                        IsResolveHost:
                          type: boolean
                          example: false
                        IsResolveAttached:
                          type: boolean
                          example: false
                        IsDvr:
                          type: boolean
                          example: false
                        IsSourceLookup:
                          type: boolean
                          example: false
                        NextHopID:
                          type: integer
                          example: 0
                        RpfID:
                          type: integer
                          example: 0
                        LabelStack:
                          type: object
                          description: // FibMplsLabel is object returned with route dump. Struct is IsUniform bool, Label uint32, TTL uint8, Exp uint8
                          example: []
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found