openapi: 3.0.1
info:
  title: Ligato VPP Agent REST APIs
  description: Describes the REST APIs supported by the Ligato VPP Agent
  version: 3.0
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
tags:
  - name: Ligato VPP Agent
paths:
  /vpp/telemetry/runtime:
    get:
      summary:
      description: contains values returned from 'show runtime'
      tags:
        - Telemetry Plugin
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: object
                description: contains values returned from 'show runtime'
                properties:
                  threads:
                    type: array
                    description: contains values returned from 'show runtime'
                    items:
                      type: object
                      description: single runtime thread data
                      properties:
                        id:
                          type: integer
                          format: uint
                          example: 0
                        name:
                          type: string
                          description: name
                          example: ALL
                        time:
                          type: number
                          format: float64
                          example: 0
                        avg_vectors_per_node:
                          type: number
                          format: float64
                          example: 0
                        last_main_loops:
                          type: integer
                          format: uint64
                          example: 0
                        vectors_per_main_loop:
                          type: number
                          format: float64
                          example: 0
                        vector_length_per_node:
                          type: number
                          format: float64
                          example: 0
                        vector_rates_in:
                          type: number
                          format: float64
                          example: 0
                        vector_rates_out:
                          type: number
                          format: float64
                          example: 0
                        vector_rates_drop:
                          type: number
                          format: float64
                          example: 0
                        vector_rates_punt:
                          type: number
                          format: float64
                          example: 0
                        items:
                          $ref: '#/components/schemas/items_telemetry_runtime'
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error
  /vpp/telemetry/nodecount:
    get:
      summary:
      description: contains values returned from 'show node counters'
      tags:
        - Telemetry Plugin
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: object
                description: contains values returned from 'show node counters'
                properties:
                  counters:
                    type: array
                    description: contains values returned from 'show node counters'
                    items:
                      type: object
                      description: single node counter
                      properties:
                        value:
                          type: integer
                          format: uint64
                          example: 0
                        node:
                          type: string
                          description: node
                          example: /err/null-node
                        name:
                          type: string
                          description: name
                          example: blackholed packets
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error
  /vpp/telemetry/memory:
    get:
      summary:
      description: memory thread values
      tags:
        - Telemetry Plugin
      responses:
        '200':
          description: memory thread values
          content:
            application/json:
              schema:
                type: object
                description: memory thread values
                properties:
                  threads:
                    type: array
                    description: memory thread values
                    items:
                      type: object
                      description: memory thread values
                      properties:
                        id:
                          type: integer
                          format: uint
                          example: 0
                        name:
                          type: string
                          description:
                          example: north1
                        size:
                          type: integer
                          format: uint64
                          example: 0
                        objects:
                          type: integer
                          format: uint64
                          example: 0
                        used:
                          type: integer
                          format: uint64
                          example: 0
                        total:
                          type: integer
                          format: uint64
                          example: 0
                        free:
                          type: integer
                          format: uint64
                          example: 0
                        reclaimed:
                          type: integer
                          format: uint64
                          example: 0
                        overhead:
                          type: integer
                          format: uint64
                          example: 0
                        pages:
                          type: integer
                          format: uint64
                          example: 0
                        page_size:
                          type: integer
                          format: uint64
                          example: 0
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error
components:
  schemas:
    items_telemetry_runtime:
      type: array
      description: single runtime item
      items:
        type: object
        properties:
          index:
            type: integer
            format: uint
            example: 0
          name:
            type: string
            example: null-node
          state:
            type: string
            example:
          calls:
            type: integer
            format: uint64
            example: 0
          vectors:
            type: integer
            format: uint64
            example: 0
          suspends:
            type: integer
            format: uint64
            example: 0
          clocks:
            type: number
            format: float64
          vectors_per_call:
            type: number
            format: float64