openapi: 3.0.1
info:
  title: VPP Agent Telemetry Memory
  description: VPP Agent GET Telemetry Memory REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /vpp/telemetry/memory:
    get:
      summary:
      description: memory thread values
      responses:
        '200':
          description: memory thread values
          content:
            application/json:
              schema:
                type: object
                description: memory thread values
                properties:
                  threads:
                    type: array
                    description: memory thread values
                    items:
                      type: object
                      description: memory thread values
                      properties:
                        id:
                          type: integer
                          format: uint
                          example: 0
                        name:
                          type: string
                          description: name
                          example: name
                        size:
                          type: integer
                          format: uint64
                          example: 0
                        objects:
                          type: integer
                          format: uint64
                          example: 0
                        used:
                          type: integer
                          format: uint64
                          example: 0
                        total:
                          type: integer
                          format: uint64
                          example: 0
                        free:
                          type: integer
                          format: uint64
                          example: 0
                        reclaimed:
                          type: integer
                          format: uint64
                          example: 0
                        overhead:
                          type: integer
                          format: uint64
                          example: 0
                        pages:
                          type: integer
                          format: uint64
                          example: 0
                        page_size:
                          type: integer
                          format: uint64
                          example: 0
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error
