openapi: 3.0.1
info:
  title: KV Scheduler Key Flag Stats Derived
  description: Key Value Scheduler GET Scheduler Flag Stats by Derived
  version: 0.9
  contact:
    name: Chris Metz
    email: cymetz@gmail.com
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
tags:
  - name: Ligato KV Scheduler
paths:
  /scheduler/flag-stats:
    get:
      tags:
        - flag-stats
      parameters:
        - name: flag
          in: query
          required: true
          schema:
            type: string
            description: query parameter is the value flag name contained in ../plugins/kvscheduler/value_flags.go
            example: derived
      responses:
        '200':
          description: derived flag-stats
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalCount:
                    type: integer
                    descriptor: total count of per-flag instances
                    example: 31
                  PerValueCount:
                    type: object
                    description: see plugins/kvscheduler/value_flags.go
                    properties:
                      <base-key>:
                        type: integer
                        format: int32
                        example: 16
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error