openapi: 3.0.1
info:
  title: Title
  description: Title REST API
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/foo:
    get:
      summary:
      description:
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: array
                description:
                items:
                  type: object
                  description: an individual Linux Interface and meta object
                  properties:
                    main:
                      type: object
                      properties:
                          first_prop:
                            type: string
                            example: first
                          2nd_prop:
                            type: string
                            enum:
                              - item 1
                              - item 2
                              - item 3
                            example: item 1
                          3rd_prop:
                            type: object
                            description: description text
                            properties:
                              3a_prop:
                                type: string
                                example: "3a"
                              reference:
                                type: string
                                example: "/reference_string"
                          4th_prop:
                            type: string
                            example: number4
                          5th_prop:
                            type: array
                            description: array with no name value; "5thprop':' [val1, val2, ...]"
                            items:
                              type: string
                              format: ipv4
                              example: 192.168.22.1/24
                          6th_prop:
                            type: array
                            description: array with key value pairs
                            items:
                              type: object
                              properties:
                                first_name:
                                  type: string
                                  example: joe
                                last_name:
                                  type: string
                                  example: smith
                    meta:
                      $ref: '#/components/schemas/interface_meta'
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: not found
components:
  schemas:
    interface_meta:
        type: object
        properties:
          first_meta_prop:
            type: integer
            example: 6
          second_meta_prop:
            type: integer
            example: 0
