openapi: 3.0.1
info:
  title: Ligato VPP Agent REST APIs
  description: Describes the REST APIs supported by the Ligato VPP Agent
  version: 3.0
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
tags:
  - name: Ligato VPP Agent
paths:
  /info/version:
    get:
      summary: Returns VPP Agent version info
      tags:
        - Version
      responses:
        '200':
          description: IPsec SA data
          content:
            application/json:
              schema:
                type: object
                properties:
                  App:
                    type: string
                    example: vpp-agent
                  Version:
                    type: string
                    example: v3.2.0-alpha-19-g00aadb60d-dirty
                  GitCommit:
                    type: string
                    example: 00aadb60d4789d5066a0354ea62ea9140c67d5fe
                  GitBranch:
                    type: string
                    example: version-rest-handler
                  BuildUser:
                    type: string
                    example: root
                  BuildHost:
                    type: string
                    example: a16a1f1fa74f
                  BuildTime:
                    type: integer
                    format: int64
                    example: 1593109090
                  GoVersion:
                    type: string
                    example: go1.14.4
                  OS:
                    type: string
                    example: linux
                  Arch:
                    type: string
                    example: amd64
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error