openapi: 3.0.1
info:
  title: Ligato VPP Agent REST APIs
  description: Describes the REST APIs supported by the Ligato VPP Agent
  version: 3.0
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
tags:
  - name: Ligato VPP Agent
paths:
  /dump/vpp/v2/abf:
    get:
      summary:
      description:
      tags:
        - ABF Plugin
      responses:
        '200':
          description: ABF defines ACL based forwarding
          content:
            application/json:
              schema:
                type: array
                description:
                items:
                  type: object
                  description: ABF data
                  properties:
                    abf:
                      type: object
                      properties:
                        index:
                          type: integer
                          format: uint32
                          description: ABF index (unique identifier)
                          example: 1
                        acl_name:
                          type: string
                          description: Name of the associated access list
                          example: acl1
                        attached_interfaces:
                          $ref: '#/components/schemas/attached_interfaces'
                        forwarding_paths:
                          $ref: '#/components/schemas/forwarding_paths'
                    abf_meta:
                      $ref: '#/components/schemas/abf_meta'
        '404':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: error message
                example: 404 page not found
        '500':
          description: error
          content:
            application/json:
              schema:
                type: string
                description: something not working properly in system
                example: 500 Internal server error
components:
  schemas:
    abf_meta:
      type: object
      properties:
        policy_id:
          type: integer
          format: uint32
          example: 6
    attached_interfaces:
      type: array
      description: List of interfaces attached to the ABF
      items:
        type: object
        properties:
          input_interface:
            type: string
            example: tap1
          priority:
            type: integer
            format: uint32
            example: 6
          is_ipv6:
            type: boolean
            example: false
    forwarding_paths:
      type: array
      description: List of forwarding paths added to the ABF policy
      items:
        type: object
        properties:
          next_hop_ip:
            type: string
            example: 192.168.11.1
          interface_name:
            type: string
            example: tap3
          weight:
            type: integer
            format: uint32
            example: 6
          preference:
            type: integer
            format: uint32
            example: 6
          dvr:
            type: boolean
            example: false
