openapi: 3.0.1
info:
  title: VPP Agent Ethernet Interface
  description: VPP Agent for GET Ethernet Interfaces
  version: 0.9
servers:
  - url: 'http://{hostServer}:9191'
    variables:
      hostServer:
        default: locahost
        description: localhost or VPP agent server IP address
paths:
  /dump/vpp/v2/interfaces/ethernet:
    get:
      summary: list of Ethernet Interfaces
      description:
      responses:
        '200':
          description: list of Ethernet Interfaces
          content:
            application/json:
              schema:
                type: array
                description: list of Ethernet Interfaces
                items:
                  type: object
                  properties:
                    sw_if_index:
                      type: object
                      description: sw_if_index used to index array of interface objects
                      properties:
                        interface:
                          type: object
                          description: properties fields defined in proto/ligato/vpp/interfaces/interface.pb.go
                          properties:
                            name:
                              type: string
                              example: GigabitEthernet0/8/0
                              description: logical name for the interface, must be unique across all configured VPP interfaces
                            type:
                              type: string
                              required: boolean
                              description: interface type and must match actual link
                              enum:
                                - UNDEFINED_TYPE
                                - SUB_INTERFACE
                                - SOFTWARE_LOOPBACK
                                - DPDK
                                - MEMIF
                                - TAP
                                - AF_PACKET
                                - VXLAN_TUNNEL
                                - VMXNET3_INTERFACE
                                - BOND_INTERFACE
                                - GRE_TUNNEL
                                - GTPU_TUNNEL
                                - IPIP_TUNNEL
                              example: DPDK
                            enabled:
                              type: boolean
                              description: Enabled controls if the interface should be UP
                              example: true
                            physAddress:
                              type: string
                              description: interface physical address; random address assigned if left empty
                              example: 08:00:27:da:0d:6b
                            ipAddresses:
                              type: string
                              description: IPAddresses define list of IP addresses for the interface and must be defined in the format of <ipAddress>/<ipPrefix>.
                              example: 172.30.1.1/24
                            vrf:
                              type: uint32
                              description: ID of VRF table that the interface is assigned to.
                              example: 1
                            set_dhcp_client:
                              type: boolean
                            mtu:
                              type: integer
                              example: 9206
                              description: maximum frame size on wire
                            unnumbered:
                              type: string
                              description: unnumbered interface
                              properties:
                                interfaceWithIp:
                                  type: string
                                  description: name of interface to borrow IP address from
                            rxModes:
                              type: object
                              description: rx mode for interface
                              properties:
                                queue:
                                  type: uint32
                                  example: 1
                                mode:
                                  type: string
                                  enum:
                                    - UNKNOWN
                                    - POLLING
                                    - INTERRUPT
                                    - ADAPTIVE
                                    - DEFAULT
                                  example: POLLING
                                defaultMode:
                                  type: boolean
                            rxPlacements:
                              type: object
                              description: rxPlacement
                              properties:
                                queue:
                                  type: uint32
                                  example: 1
                                worker:
                                  type: uint32
                                  example: 1
                                mainThread:
                                  type: boolean
                        interface_meta:
                                $ref: '#/components/schemas/interface_meta'
        '404':
           description: error
           content:
             application/json:
               schema:
                 type: string
                 description: error message
                 example: not found
components:
  schemas:
    interface_meta:
      type: object
      description: properties defined in plugins/vpp/ifplugin/vppcalls/interface_handler_api.go
      properties:
        sw_if_index:
          type: uint32
          description: sw_if_index used to index array of interface objects
          example: 1
        sub_sw_if_index:
          type: uint32
          example: 3
        l2_address:
          type: string
          example: NDwAAAAB
        internal_name:
          type: string
          example: GigabitEthernet0/8/0
        is_admin_state_up:
          type: boolean
          example: true
        is_link_state_up:
          type: boolean
          example: true
        link_duplex:
          type: uint32
          example: 2
        link_mtu:
          type: uint32
          example: 9206
        mtu:
          type: uint32
          description: per-protocol mtu for L2, ... organized as array
          example: [9000, 0,0,0]
        link_speed:
          type: uint32
          example: 1000000
        sub_id:
          type: uint32
          example: 0
        tag:
          type: string
          example: ""
        dhcp:
          nullable: boolean
          example: null
          # look into handling with component
        vrf_ipv4:
          type: uint32
          example: 0
        vrf_ipv6:
          type: uint32
          example: 0
        pci:
          type: uin32
          example: 0


